# Generated by Django 4.2.9 on 2024-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_chatsession_is_active_chatsession_request_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="request_type",
            field=models.IntegerField(default=-1),
        ),
    ]
